class Constants {
  static String dummyTextShort = """
  Sed elementum tempus egestas sed sed risus pretium quam vulputate. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Tellus integer feugiat scelerisque varius. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Faucibus purus in massa tempor nec feugiat. Nunc mattis enim ut tellus elementum sagittis vitae. Non tellus orci ac auctor. Amet tellus cras adipiscing enim eu. Feugiat scelerisque varius morbi enim. Scelerisque eu ultrices vitae auctor. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Enim sed faucibus turpis in eu mi. Urna cursus eget nunc scelerisque viverra mauris in. Libero enim sed faucibus turpis in eu. Nec nam aliquam sem et tortor. Cursus vitae congue mauris rhoncus aenean vel.
  """;

  static String dummyTextLong = """
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat nam at lectus urna duis convallis convallis tellus. Varius duis at consectetur lorem donec. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Non blandit massa enim nec dui. Vitae et leo duis ut diam quam nulla porttitor massa. Enim praesent elementum facilisis leo vel fringilla est. Lectus mauris ultrices eros in. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Elementum eu facilisis sed odio morbi quis commodo odio.

Sed elementum tempus egestas sed sed risus pretium quam vulputate. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Tellus integer feugiat scelerisque varius. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Faucibus purus in massa tempor nec feugiat. Nunc mattis enim ut tellus elementum sagittis vitae. Non tellus orci ac auctor. Amet tellus cras adipiscing enim eu. Feugiat scelerisque varius morbi enim. Scelerisque eu ultrices vitae auctor. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Enim sed faucibus turpis in eu mi. Urna cursus eget nunc scelerisque viverra mauris in. Libero enim sed faucibus turpis in eu. Nec nam aliquam sem et tortor. Cursus vitae congue mauris rhoncus aenean vel.

Vel quam elementum pulvinar etiam non. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Euismod quis viverra nibh cras pulvinar mattis. Tincidunt ornare massa eget egestas purus viverra accumsan in nisl. Erat nam at lectus urna duis convallis convallis tellus id. Tincidunt vitae semper quis lectus nulla at volutpat diam. Odio aenean sed adipiscing diam donec. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean. Mus mauris vitae ultricies leo integer malesuada nunc vel risus.

Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum integer. Magna fringilla urna porttitor rhoncus dolor purus non. Proin gravida hendrerit lectus a. Praesent semper feugiat nibh sed pulvinar proin. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Consectetur adipiscing elit duis tristique sollicitudin. Pretium nibh ipsum consequat nisl vel pretium. Consequat mauris nunc congue nisi vitae suscipit tellus. Morbi tempus iaculis urna id. Sagittis orci a scelerisque purus semper eget duis at tellus. Enim sed faucibus turpis in eu mi. Eget egestas purus viverra accumsan in nisl nisi. In hac habitasse platea dictumst quisque. Pretium nibh ipsum consequat nisl. Ultrices sagittis orci a scelerisque purus. Suspendisse faucibus interdum posuere lorem ipsum dolor sit. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Amet tellus cras adipiscing enim eu turpis egestas pretium aenean. Viverra mauris in aliquam sem fringilla ut morbi.

In iaculis nunc sed augue lacus viverra. Mauris sit amet massa vitae tortor. Vel pharetra vel turpis nunc eget lorem. Iaculis nunc sed augue lacus. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Nisl pretium fusce id velit. Nisl suscipit adipiscing bibendum est ultricies. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Ut tellus elementum sagittis vitae et leo duis ut diam. Convallis posuere morbi leo urna molestie at elementum eu. Nisl tincidunt eget nullam non. Sed faucibus turpis in eu mi bibendum neque egestas. Euismod elementum nisi quis eleifend quam adipiscing vitae.
  """;
}
